# -*- coding: utf-8 -*-
"""fused-unet-dcenet-v4-final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14C1t299tN0CydvvjyTbjnlxPazS_WDfX
"""

!pip install piq lpips kornia
!pip install --upgrade piq

import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

import random
import kornia

import os
import time
import sys

import cv2
import numpy as np

import torchvision.transforms as T
import torchvision.transforms.functional as TF
from torchvision.models import vgg16, VGG16_Weights

print(f"PyTorch version: {torch.__version__}")

device = torch.device("cuda" if torch.cuda.is_available() else 'cpu')
print(f"Device: {device}")

class Augmentation:
    def __init__(self):
        self.blur = T.GaussianBlur(kernel_size=(3, 3), sigma=(0.1, 0.5))
        self.noise_std = 0.02

    def __call__(self, low_img, high_img):
        # 1. Random Horizontal & Vertical flip
        if random.random() > 0.5:
            low_img = TF.hflip(low_img)
            high_img = TF.hflip(high_img)

        if random.random() > 0.5:
            low_img = TF.vflip(low_img)
            high_img = TF.vflip(high_img)

        # Randomly add blur
        if random.random() > 0.3:
            low_img = self.blur(low_img)

        # 3. Add Gaussian Noise
        noise = torch.randn_like(low_img) * self.noise_std
        low_img = torch.clamp(low_img + noise, 0, 1)

        return low_img, high_img

class LLIEDataset(Dataset):
    def __init__(self, low_dir, high_dir=None, random_samples=None, patch_size=256):
        super(LLIEDataset, self).__init__()
        self.low_dir = low_dir
        self.high_dir = high_dir
        self.files = sorted(os.listdir(low_dir))
        if random_samples:
            self.random_samples = len(self.files) if len(self.files)<random_samples else random_samples
            self.files = random.sample(self.files, self.random_samples)
        self.patch_size = patch_size
        self.aug = Augmentation()


    def __len__(self):
        return len(self.files)


    def __getitem__(self, idx):
        low_path = os.path.join(self.low_dir, self.files[idx])
        low = cv2.imread(low_path)
        low = cv2.cvtColor(low, cv2.COLOR_BGR2RGB)
        low = low.astype(np.float32)/255.0
        H, W, _ = low.shape
        # random crop
        y = np.random.randint(0, W - self.patch_size)
        x = np.random.randint(0, H - self.patch_size)
        low = low[x:x+self.patch_size, y:y+self.patch_size]
        # to tensor
        low = torch.from_numpy(low.copy()).permute(2,0,1)

        if self.high_dir:
            high_path = os.path.join(self.high_dir, self.files[idx])
            high = cv2.imread(high_path)
            high = cv2.cvtColor(high, cv2.COLOR_BGR2RGB)
            high = high.astype(np.float32)/255.0
            high = high[x:x+self.patch_size, y:y+self.patch_size]
            # totensor
            high = torch.from_numpy(high.copy()).permute(2,0,1)
            return self.aug(low, high)

        return low

# Double Convolution Block (The building block)
class DoubleConv(nn.Module):
    def __init__(self, in_channels, out_channels):
        super(DoubleConv, self).__init__()
        self.double_conv = nn.Sequential(
            nn.Conv2d(in_channels, out_channels, kernel_size=3, padding=1, bias=False),
            nn.BatchNorm2d(out_channels),
            nn.PReLU(),
            nn.Conv2d(out_channels, out_channels, kernel_size=3, padding=1, bias=False),
            nn.BatchNorm2d(out_channels),
            nn.PReLU()
        )

    def forward(self, x):
        return self.double_conv(x)


# The Retinex U-Net (Architecture)
class RetinexUNet(nn.Module):
    def __init__(self, in_channels=3, out_channels=3):
        super(RetinexUNet, self).__init__()
        features = [32, 64, 128, 256]

        # Encoder
        self.inc = DoubleConv(in_channels, features[0])
        self.down1 = nn.Sequential(nn.MaxPool2d(2), DoubleConv(features[0], features[1]))
        self.down2 = nn.Sequential(nn.MaxPool2d(2), DoubleConv(features[1], features[2]))
        self.down3 = nn.Sequential(nn.MaxPool2d(2), DoubleConv(features[2], features[3]))

        # Bottleneck
        self.bottleneck = nn.Sequential(nn.MaxPool2d(2), DoubleConv(features[3], features[3] * 2))

        # Decoder
        self.up1 = nn.ConvTranspose2d(features[3] * 2, features[3], kernel_size=2, stride=2)
        self.dec1 = DoubleConv(features[3] * 2, features[3])

        self.up2 = nn.ConvTranspose2d(features[3], features[2], kernel_size=2, stride=2)
        self.dec2 = DoubleConv(features[2] * 2, features[2])

        self.up3 = nn.ConvTranspose2d(features[2], features[1], kernel_size=2, stride=2)
        self.dec3 = DoubleConv(features[1] * 2, features[1])

        self.up4 = nn.ConvTranspose2d(features[1], features[0], kernel_size=2, stride=2)
        self.dec4 = DoubleConv(features[0] * 2, features[0])

        # Final Layer to predict Illumination Map
        self.outc = nn.Sequential(
            nn.Conv2d(features[0], out_channels, kernel_size=1),
            nn.Sigmoid()
        )

    def forward(self, x_low):
        # Encoder Pathway
        e1 = self.inc(x_low)
        e2 = self.down1(e1)
        e3 = self.down2(e2)
        e4 = self.down3(e3)
        b = self.bottleneck(e4)

        # Decoder Pathway with Skip Connections
        d1 = self.dec1(torch.cat([e4, self.up1(b)], dim=1))
        d2 = self.dec2(torch.cat([e3, self.up2(d1)], dim=1))
        d3 = self.dec3(torch.cat([e2, self.up3(d2)], dim=1))
        d4 = self.dec4(torch.cat([e1, self.up4(d3)], dim=1))

        # PREDICT ILLUMINATION MAP
        illumination = self.outc(d4)
        illumination = torch.clamp(illumination, min=0.01) # Avoid division by zero

        # APPLY RETINEX: Enhanced = Input / Illumination
        # This keeps the original edges SHARP
        enhanced = x_low / illumination
        enhanced = torch.clamp(enhanced, 0, 1)

        return enhanced, illumination

class RetinexLoss(nn.Module):
    def __init__(self):
        super().__init__()
        self.l1 = nn.L1Loss()
        self.mse = nn.MSELoss()
        self.device = 'cuda' if torch.cuda.is_available() else 'cpu'
        # VGG for Texture Realism
        vgg = vgg16(weights=VGG16_Weights.IMAGENET1K_V1).features[:16].to(self.device).eval()
        for param in vgg.parameters():
            param.requires_grad = False
        self.vgg = vgg

    def forward(self, enhanced, illumination, low_input, high_gt):
        # 1. Reconstruction & Structure (Natural Feel)
        loss_recon = 0.8 * self.l1(enhanced, high_gt) + 0.2 * self.mse(enhanced, high_gt)
        loss_ssim = 1 - self.ssim_loss(enhanced, high_gt)

        # 2. DSLR Focus Loss (Edge Sharpness)
        loss_focus = self.laplacian_focus_loss(enhanced, high_gt)

        # 3. Content-Adaptive Exposure (Day/Night Balance)
        with torch.no_grad():
            low_mean = torch.mean(low_input, dim=(1,2,3))
            target_exp = torch.where(low_mean < 0.3, torch.tensor(0.6).to(self.device), low_mean + 0.05)
        avg_intensity = F.avg_pool2d(enhanced, 16).mean(dim=(1,2,3))
        loss_exp = torch.mean((avg_intensity - target_exp)**2)

        # 4. Illumination & Denoise (Anti-Patch & Anti-Noise)
        loss_tv_illum = self.tv_loss(illumination)
        # To remove noise from Final image (Edge-aware denoising)
        loss_denoise = self.edge_aware_tv_loss(enhanced)

        # 5. Color & Texture Realism
        loss_color = 1 - F.cosine_similarity(torch.mean(enhanced, dim=(2,3)),
                                             torch.mean(high_gt, dim=(2,3)), dim=1).mean()
        loss_vgg = self.l1(self.vgg(enhanced), self.vgg(high_gt))

        # --- FINAL BALANCED WEIGHTS ---
        # SSIM(25) + Focus(15) -> DSLR Clarity
        # Exp(10) -> Day/Night balance
        # TV_Illum(20) -> Patches hatane ke liye
        total_loss = (1.0 * loss_recon) + (25.0 * loss_ssim) + \
                     (15.0 * loss_focus) + (10.0 * loss_exp) + \
                     (20.0 * loss_tv_illum) + (10.0 * loss_denoise) + \
                     (5.0 * loss_color) + (0.5 * loss_vgg)

        return total_loss

    def laplacian_focus_loss(self, pred, gt):
        lap = torch.tensor([[0, 1, 0], [1, -4, 1], [0, 1, 0]], dtype=torch.float32).view(1,1,3,3).to(self.device)
        def get_lap(img):
            return torch.cat([F.conv2d(img[:, i:i+1, :, :], lap, padding=1) for i in range(3)], dim=1)
        return self.l1(get_lap(pred), get_lap(gt))

    def edge_aware_tv_loss(self, img):
        h_x = img[:, :, 1:, :] - img[:, :, :-1, :]
        w_x = img[:, :, :, 1:] - img[:, :, :, :-1]
        return torch.mean(torch.exp(-15 * torch.abs(h_x)) * torch.abs(h_x)) + \
               torch.mean(torch.exp(-15 * torch.abs(w_x)) * torch.abs(w_x))

    def ssim_loss(self, img1, img2, window_size=11):
        mu1 = F.avg_pool2d(img1, window_size, stride=1, padding=window_size//2)
        mu2 = F.avg_pool2d(img2, window_size, stride=1, padding=window_size//2)
        s1q = F.avg_pool2d(img1*img1, window_size, stride=1, padding=window_size//2) - mu1**2
        s2q = F.avg_pool2d(img2*img2, window_size, stride=1, padding=window_size//2) - mu2**2
        s12 = F.avg_pool2d(img1*img2, window_size, stride=1, padding=window_size//2) - mu1*mu2
        c1, c2 = 0.01**2, 0.03**2
        return (((2*mu1*mu2 + c1)*(2*s12 + c2)) / ((mu1**2 + mu2**2 + c1)*(s1q + s2q + c2))).mean()

    def tv_loss(self, obj):
        batch_size, channels, h, w = obj.size()
        h_tv = torch.pow((obj[:,:,1:,:] - obj[:,:,:-1,:]), 2).sum()
        w_tv = torch.pow((obj[:,:,:,1:] - obj[:,:,:,:-1]), 2).sum()
        return (h_tv/((h-1)*w) + w_tv/(h*(w-1))) / (batch_size * channels)

class UNetTrainer:
    def __init__(self, model, criterion, optimizer, scheduler):
        self.model = model
        self.criterion = criterion
        self.optimizer = optimizer
        self.scheduler = scheduler
        self.device = device or torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        self.model.to(self.device)
        self.criterion.to(self.device)
        self.best_loss = float('inf')
        self.best_model_path = None

    def show_live_stats(self, running_loss, n_batches, idx, start_time, epoch, total_epochs):
        # Stats calculation
        # Formatting the progress bar
        current_step = idx + 1
        avg_loss = running_loss / current_step

        # create [====>.....] string
        bar_width = 30
        progress = int(current_step / n_batches * bar_width)
        bar = '='* progress + '=>' + "." * (bar_width - progress - 1)

        # Timing
        elapsed = time.time() - start_time
        step_time = (elapsed / current_step) * 1000 # 1000 ms per batch

        # The Magic line
        output = (f"\rEpoch: {epoch}/{total_epochs} - "
                  f"{current_step}/{n_batches} [{bar}]"
                  f"- {step_time:.0f}ms/step - train_loss: {avg_loss:.4f}")

        sys.stdout.write(output)
        sys.stdout.flush()

    def _train_epoch(self, loader, epoch, total_epochs):
        self.model.train()
        train_loss = 0.0
        n_batches = len(loader)
        start_time = time.time()

        for i, (x, y) in enumerate(loader):
            self.optimizer.zero_grad()
            x = x.to(self.device)
            pred, illum = self.model(x)
            loss = self.criterion(pred, illum, x, y.to(self.device))
            loss.backward()
            torch.nn.utils.clip_grad_norm_(self.model.parameters(), 0.1)
            self.optimizer.step()
            train_loss += loss.item()
            self.show_live_stats(train_loss, n_batches, i, start_time, epoch, total_epochs)
        return train_loss / n_batches

    def _validate(self, loader):
        self.model.eval()
        val_loss = 0.0

        with torch.no_grad():
            for x,y in loader:
                x = x.to(self.device)
                pred, illum = self.model(x)
                loss = self.criterion(pred, illum, x, y.to(self.device))
                val_loss += loss.item()

        val_loss = val_loss / len(loader)
        sys.stdout.write(f" - val_loss: {val_loss:.4f}")
        sys.stdout.flush()
        return val_loss



    def fit(self, train_loader, val_loader, epochs, save_model_path, model_name):
        self.best_model_path = os.path.join(save_model_path, model_name)
        for epoch in range(1, epochs+1):
            train_loss = self._train_epoch(train_loader, epoch, epochs)
            val_loss = self._validate(val_loader)
            diff = abs(train_loss - val_loss)
            if (diff < 5) and (val_loss < self.best_loss):
                old_best = self.best_loss
                self.best_loss = val_loss
                torch.save(self.model.state_dict(), self.best_model_path)
                sys.stdout.write(f" - val_loss improved from {old_best:.4f} to {val_loss:.4f} (diff: {diff:.4f}) and model saved!")
                sys.stdout.flush()
            if self.scheduler:
                self.scheduler.step()
            print()


    def predict(self, x):
        self.model.eval()
        with torch.no_grad():
            return self.model(x.to(self.device))

    def load_best_model(self):
        if not self.best_model_path:
            raise ValueError("No best model found. Please train the model first.")
        self.model.load_state_dict(torch.load(self.best_model_path))

    def load_best_model_for_inference(self, path=None):
        if path:
            self.best_model_path = path
            self.model.load_state_dict(torch.load(self.best_model_path))
            print(f"Best model from {self.best_model_path} loaded succeessfully!")

batch_size=8
patch_size=256
random_samples = 16


save_model_path = "/kaggle/working"
unet_model_name = "best-unet-model.pth"
dcenet_model_name = "best-dcenet-model.pth"
fused_model_name = "best-fused-model.pth"


images_path = "/kaggle/input/datasets/shaileshkumarvishwak/custom-llie-dataset/Custom-LLIE-Dataset"

train_dataset = LLIEDataset(low_dir = os.path.join(images_path, "Train/low"),
                            high_dir = os.path.join(images_path, "Train/bright"),
                            patch_size = patch_size,
                            random_samples=random_samples)

val_dataset = LLIEDataset(low_dir = os.path.join(images_path, "Val/low"),
                          high_dir = os.path.join(images_path, "Val/bright"),
                          patch_size=patch_size,
                          random_samples=random_samples)

test_dataset = LLIEDataset(low_dir = os.path.join(images_path, "Test/low"),
                          high_dir = None,
                          patch_size=patch_size,
                          random_samples=random_samples)

train_loader = DataLoader(train_dataset,
                          batch_size=batch_size,
                          shuffle=True,
                          pin_memory=True)

val_loader = DataLoader(val_dataset,
                        batch_size=batch_size,
                        shuffle=False)

test_loader = DataLoader(test_dataset,
                        batch_size=batch_size,
                        shuffle=False)

print(f"Length of train loader: {len(train_loader)}")
print(f"Length of val loader: {len(val_loader)}")
print(f"Length of test loader: {len(test_loader)}")

unet_num_epochs = 5

unet_model = RetinexUNet()
criterion = RetinexLoss()

optimizer = optim.AdamW(unet_model.parameters(), lr=1e-4, betas=(0.9, 0.999), weight_decay=0.01)
scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=unet_num_epochs, eta_min=1e-6)
unet_trainer = UNetTrainer(unet_model, criterion, optimizer, scheduler)

# unet_trainer.load_best_model_for_inference("/kaggle/input/models/shaileshkumarvishwak/llie-fused-models/pytorch/default/1/best-unet-model.pth")

unet_trainer.fit(train_loader, epochs=unet_num_epochs, val_loader=val_loader, save_model_path=save_model_path, model_name=unet_model_name)

import torch
import numpy as np
from piq import ssim, psnr
import lpips

class ScoreCalculator:
    def __init__(self):
        self.device = 'cuda' if torch.cuda.is_available() else 'cpu'
        # Initialize LPIPS (AlexNet backbone is standard for speed/accuracy)
        self.lpips_vgg = lpips.LPIPS(net='vgg').to(self.device)

    def calculate_metrics(self, pred, target):
        """
        pred: Tensor [B, 3, H, W], range [0, 1]
        target: Tensor [B, 3, H, W], range [0, 1]
        """
        results = {}

        # 1. PSNR (Peak Signal-to-Noise Ratio)
        # Higher is better. Usually 20-40dB for reconstruction tasks.
        results['psnr'] = psnr(pred, target, data_range=1.0).item()

        # 2. SSIM (Structural Similarity Index)
        # Range [0, 1]. Higher is better (1.0 is perfect).
        results['ssim'] = ssim(pred, target, data_range=1.0).item()

        # 3. LPIPS (Learned Perceptual Image Patch Similarity)
        # Lower is better. Measures "perceptual" distance using deep features.
        # Note: LPIPS expects input in range [-1, 1]
        lpips_score = self.lpips_vgg(pred * 2 - 1, target * 2 - 1)
        results['lpips'] = lpips_score.mean().item()

        return results

evaluator = ScoreCalculator()

def print_evaluation_metrics(evaluator, pred, target):
    scores = evaluator.calculate_metrics(pred, target)

    return scores['psnr'], scores['ssim'], scores['lpips']

import matplotlib.pyplot as plt
def show_img(low, high, pred, with_gt=False):
    if with_gt:
        for l, h, p in zip(low, high, pred):
            plt.figure(figsize=(5, 15))
            plt.subplot(1, 3, 1)
            plt.imshow(l.permute(1,2,0).cpu())
            plt.title('Input image')

            plt.subplot(1, 3, 2)
            plt.imshow(h.permute(1, 2, 0).cpu())
            plt.title('Bright image')

            plt.subplot(1, 3, 3)
            plt.imshow(p.permute(1, 2, 0).cpu())
            plt.title('Output image')

            plt.show()
    else:
        for l, p in zip(low, pred):
            plt.figure(figsize=(5, 15))
            plt.subplot(1, 2, 1)
            plt.imshow(l.permute(1,2,0).cpu())
            plt.title('Input image')

            plt.subplot(1, 2, 2)
            plt.imshow(p.permute(1, 2, 0).cpu())
            plt.title('Output image')

            plt.show()


def visualize_results(model, loader, test_data=False, name=None):
    model.load_best_model()
    i = 1
    if test_data:
        for low in loader:
            low = low.to(device)
            if name:
                pred, _ = model.predict(low)
            else:
                pred = model.predict(low)

            show_img(low, low, pred, with_gt=False)
            if i==1:
                break
            i+=1
        return

    for low, high in loader:
        low = low.to(device)
        if name:
            pred, _ = model.predict(low)
        else:
            pred = model.predict(low)

        show_img(low, high.to(device), pred, with_gt=True)
        if i==1:
            break
        i+=1

def inference_model(model, loader, test_data=False, name=None):
    model.load_best_model()
    if test_data:
        for low in loader:
            low = low.to(device)
            if name:
                pred, _ = model.predict(low)
            else:
                pred = model.predict(low)
            show_img(low, low, pred, with_gt=False)
        return

    for low, high in loader:
        low = low.to(device)
        if name:
            pred, _ = model.predict(low)
        else:
            pred = model.predict(low)
        show_img(low, high, pred)

def calculate_scores(model, loader, name=None):
    psnr_total, ssim_total, lpips_total = 0, 0, 0
    for low, high in loader:
        high = high.to(device)
        if name:
            pred, _ = model.predict(low)
        else:
            pred = model.predict(low)

        psnr, ssim, lpips = print_evaluation_metrics(evaluator, pred, high)
        psnr_total += psnr
        ssim_total += ssim
        lpips_total += lpips

    avg_psnr = psnr_total / len(loader)
    avg_ssim = ssim_total / len(loader)
    avg_lpips = lpips_total / len(loader)

    print(f"Val PSNR: {avg_psnr:.4f}, Val SSIM: {avg_ssim:.4f}, Val LPIPS: {avg_lpips:.4f}")

calculate_scores(unet_trainer, val_loader, name='unet')

visualize_results(unet_trainer, val_loader, name='unet')

visualize_results(unet_trainer, test_loader, name='unet', test_data=True)

"""# ZERO DCE MODEL"""

class ZeroDCENet(nn.Module):
    def __init__(self, n_iter=8):
        super(ZeroDCENet, self).__init__()
        self.n_iter = n_iter

        # 7-layer CNN with symmetrical skip connections
        # Input: 3 channels (RGB)
        # Output: 3 * n_iter channels (8 iterations * 3 RGB channels = 24)

        self.relu = nn.ReLU(inplace=True)

        self.e_conv1 = nn.Conv2d(3, 32, 3, 1, 1, bias=True)
        self.e_conv2 = nn.Conv2d(32, 32, 3, 1, 1, bias=True)
        self.e_conv3 = nn.Conv2d(32, 32, 3, 1, 1, bias=True)
        self.e_conv4 = nn.Conv2d(32, 32, 3, 1, 1, bias=True)
        self.e_conv5 = nn.Sequential(nn.Conv2d(64, 32, 3, 1, 1, bias=True), self.relu)
        self.e_conv6 = nn.Sequential(nn.Conv2d(64, 32, 3, 1, 1, bias=True), self.relu)
        self.e_conv7 = nn.Sequential(nn.Conv2d(64, 3 * n_iter, 3, 1, 1, bias=True), nn.Tanh())

    def forward(self, x):
        # Encoder with Skip Connections
        x1 = self.relu(self.e_conv1(x))
        x2 = self.relu(self.e_conv2(x1))
        x3 = self.relu(self.e_conv3(x2))
        x4 = self.relu(self.e_conv4(x3))

        # Decoder
        x5 = self.e_conv5(torch.cat([x3, x4], 1))
        x6 = self.e_conv6(torch.cat([x2, x5], 1))
        alpha_map = self.e_conv7(torch.cat([x1, x6], 1)) # [B, 24, H, W]

        # Iterative Enhancement
        y = x
        # Split the 24 channels into 8 sets of 3 RGB channels
        for i in range(self.n_iter):
            a = alpha_map[:, i*3 : (i+1)*3, :, :]
            y = y + a * y * (1 - y)

        return y, alpha_map

class ZeroDCENetLoss(nn.Module):
    def __init__(self, exposure_level=0.6, weights={'recon': 1.0, 'exp': 10.0, 'col': 2.0, 'tv': 200.0, 'spa': 1.0}):
        super(ZeroDCENetLoss, self).__init__()
        self.l1 = nn.L1Loss()
        self.exp_level = exposure_level
        self.w = weights


    def forward(self, enhanced, alpha_map, low, ground_truth):

        # Spatial Consistency (Zero-DCE style)
        loss_spa = self.spatial_loss(enhanced, low)

        # Exposure Control
        loss_exp = self.exposure_loss(enhanced)

        # Color Constancy (Natural Hue Preservation)
        loss_col = self.color_loss(enhanced, ground_truth)

        # Illumination Smoothness (Total Variation on Alpha)
        loss_tv = self.tv_loss(alpha_map)

        total_loss = loss_spa + (self.w['exp'] * loss_exp) + (self.w['col'] * loss_col) + (self.w['tv'] * loss_tv)
        return total_loss

    def spatial_loss(self, enhanced, low):
        kernel = torch.tensor([[0, 1, 0], [1, -4, 1], [0, 1, 0]], dtype=torch.float32).expand(3, 1, 3, 3).to(enhanced.device)
        return torch.mean((F.conv2d(enhanced, kernel, groups=3) - F.conv2d(low, kernel, groups=3))**2)

    def exposure_loss(self, x):
        avg_intensity = F.avg_pool2d(x, 16)
        return torch.mean((avg_intensity - self.exp_level)**2)

    def color_loss(self, x, y):
        # Using Cosine Similarity to maintain RGB ratios
        x_mean = torch.mean(x, dim=(2, 3))
        y_mean = torch.mean(y, dim=(2, 3))
        return 1 - F.cosine_similarity(x_mean, y_mean, dim=1).mean()

    def tv_loss(self, alpha):
        batch_size, _, h, w = alpha.size()
        count_h = (h - 1) * w
        count_w = h * (w - 1)
        h_tv = torch.pow((alpha[:, :, 1:, :] - alpha[:, :, :h-1, :]), 2).sum()
        w_tv = torch.pow((alpha[:, :, :, 1:] - alpha[:, :, :, :w-1]), 2).sum()
        return 2 * (h_tv / count_h + w_tv / count_w) / batch_size

class DCETrainer:
    def __init__(self, model, criterion, optimizer, scheduler):
        self.model = model
        self.criterion = criterion
        self.optimizer = optimizer
        self.scheduler = scheduler
        self.device = device or torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        self.model.to(self.device)
        self.criterion.to(self.device)
        self.best_loss = float('inf')
        self.best_model_path = None

    def show_live_stats(self, running_loss, n_batches, idx, start_time, epoch, total_epochs):
        # Stats calculation
        # Formatting the progress bar
        current_step = idx + 1
        avg_loss = running_loss / current_step

        # create [====>.....] string
        bar_width = 30
        progress = int(current_step / n_batches * bar_width)
        bar = '='* progress + '=>' + "." * (bar_width - progress - 1)

        # Timing
        elapsed = time.time() - start_time
        step_time = (elapsed / current_step) * 1000 # 1000 ms per batch

        # The Magic line
        output = (f"\rEpoch: {epoch}/{total_epochs} - "
                  f"{current_step}/{n_batches} [{bar}]"
                  f"- {step_time:.0f}ms/step - train_loss: {avg_loss:.4f}")

        sys.stdout.write(output)
        sys.stdout.flush()

    def _train_epoch(self, loader, epoch, total_epochs):
        self.model.train()
        train_loss = 0.0
        n_batches = len(loader)
        start_time = time.time()

        for i, (x, y) in enumerate(loader):
            x = x.to(self.device)
            self.optimizer.zero_grad()
            output, alpha_map = self.model(x)
            loss = self.criterion(output, alpha_map, x, y.to(device))
            loss.backward()
            torch.nn.utils.clip_grad_norm_(self.model.parameters(), 0.1)
            self.optimizer.step()
            train_loss += loss.item()
            self.show_live_stats(train_loss, n_batches, i, start_time, epoch, total_epochs)
        return train_loss/n_batches

    def _validate(self, loader):
        self.model.eval()
        val_loss = 0.0
        with torch.no_grad():
            for x,y in loader:
                x = x.to(self.device)
                pred, alpha_map = self.model(x)
                loss = self.criterion(pred, alpha_map, x, y.to(device))
                val_loss += loss.item()

        val_loss = val_loss / len(loader)
        sys.stdout.write(f" - val_loss: {val_loss:.4f}")
        sys.stdout.flush()
        return val_loss



    def fit(self, train_loader, val_loader, epochs, save_model_path, model_name):
        if self.best_model_path is None:
            self.best_model_path = os.path.join(save_model_path, model_name)
        for epoch in range(1, epochs+1):
            train_loss = self._train_epoch(train_loader, epoch, epochs)
            val_loss = self._validate(val_loader)
            diff = abs(train_loss - val_loss)
            if (diff < 5) and (val_loss < self.best_loss):
                old_best = self.best_loss
                self.best_loss = val_loss
                torch.save(self.model.state_dict(), self.best_model_path)
                sys.stdout.write(f" - val_loss improved from {old_best:.4f} to {val_loss:.4f} (diff: {diff:.4f}) and model saved!")
                sys.stdout.flush()
            if self.scheduler:
                self.scheduler.step()
            print()



    def predict(self, x):
        with torch.no_grad():
            return self.model(x.to(self.device))


    def load_best_model(self):
        if not self.best_model_path:
            raise ValueError("No best model found. Please train the model first.")
        self.model.load_state_dict(torch.load(self.best_model_path))

    def load_best_model_for_inference(self, path=None):
        if path:
            self.best_model_path = path
            self.model.load_state_dict(torch.load(self.best_model_path))
            print(f"Best model from {self.best_model_path} loaded succeessfully!")

dce_num_epochs = 5

dce_model = ZeroDCENet(n_iter=8)
criterion = ZeroDCENetLoss(exposure_level=0.6)
optimizer = optim.AdamW(dce_model.parameters(), lr=1e-4, betas=(0.9, 0.999), weight_decay=0.01)
scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=dce_num_epochs, eta_min=1e-6)
dce_trainer = DCETrainer(dce_model, criterion, optimizer, scheduler)

# dce_trainer.load_best_model_for_inference("/kaggle/input/models/shaileshkumarvishwak/llie-fused-models/pytorch/default/1/best-dcenet-model.pth")

dce_trainer.fit(train_loader, epochs=dce_num_epochs, val_loader=val_loader, save_model_path=save_model_path, model_name=dcenet_model_name)

calculate_scores(dce_trainer, val_loader, name='dce')

visualize_results(dce_trainer, val_loader, name='dce')

visualize_results(dce_trainer, test_loader, test_data=True, name='dce')

"""# FUSED MODEL"""

class DenoiseBlock(nn.Module):
    def __init__(self, channels):
        super(DenoiseBlock, self).__init__()
        # Use Dilated Convolutions to see more context without losing resolution
        self.conv = nn.Sequential(
            nn.Conv2d(channels, channels, 3, padding=2, dilation=2),
            nn.PReLU(),
            nn.Conv2d(channels, channels, 3, padding=1),
            nn.PReLU()
        )
    def forward(self, x):
        return x + self.conv(x) # Residual connection preserves sharpness

class ColorCorrection(nn.Module):
    def __init__(self):
        super(ColorCorrection, self).__init__()
        self.pointwise = nn.Sequential(
            nn.Conv2d(3, 16, 1),
            nn.PReLU(),
            nn.Conv2d(16, 3, 1),
            nn.Sigmoid()
        )
    def forward(self, x):
        # To subtle scale image colors
        return x * self.pointwise(x)



class FusionModel(nn.Module):
    def __init__(self, retinex_model, zerodce_model):
        super(FusionModel, self).__init__()

        self.retinex_net = retinex_model
        self.zerodce_net = zerodce_model

        # Pre-trained models freeze for eval mode
        for param in self.retinex_net.parameters():
            param.requires_grad = False
        for param in self.zerodce_net.parameters():
            param.requires_grad = False

        self.retinex_net.eval()
        self.zerodce_net.eval()

        # Channels: Retinex(3) + ZeroDCE(3) + Alpha(24) + Input(3) = 33
        self.feature_extractor = nn.Sequential(
            nn.Conv2d(33, 64, kernel_size=3, padding=1),
            nn.PReLU(),
            nn.Conv2d(64, 32, kernel_size=3, padding=1),
            nn.PReLU()
        )

        # Attention mask it decides which model works better where
        self.attention_mask = nn.Sequential(
            nn.Conv2d(32, 3, kernel_size=1),
            nn.Sigmoid()
        )

        # 2. Refinement head to remove grayish look and fix contrast level
        self.refiner = nn.Sequential(
            nn.Conv2d(32, 3, kernel_size=1),
            nn.Tanh() # between -1 to 1 for "fine-tuning"
        )


    def forward(self, x):
        with torch.no_grad():
            out_retinex, _ = self.retinex_net(x)
            out_zerodce, alpha_map = self.zerodce_net(x)

        # Fuse every features from retinex and zero dce models
        combined_features = torch.cat([out_retinex, out_zerodce, alpha_map, x], dim=1)
        feat = self.feature_extractor(combined_features)

        # Attention Blending to preserve sharpness
        # mask = 1 means Retinex heavy, and mask = 0 means ZeroDCE heavy
        mask = self.attention_mask(feat)
        fused = mask * out_retinex + (1 - mask) * out_zerodce

        # Residual Refinement (to remoce greyish tone)
        # Adding a little learned contrast in fusion
        refinement = self.refiner(feat)
        final_output = fused + 0.1 * refinement # 0.1 for factor stability

        return torch.clamp(final_output, 0, 1), alpha_map

class FusionLoss(nn.Module):
    def __init__(self, exp_level=0.62):
        super(FusionLoss, self).__init__()
        self.device = 'cuda' if torch.cuda.is_available() else 'cpu'
        self.l1 = nn.L1Loss()
        self.mse = nn.MSELoss()
        self.exp_level = exp_level

        vgg = vgg16(weights=VGG16_Weights.IMAGENET1K_V1).features[:16].to(self.device).eval()
        for param in vgg.parameters():
            param.requires_grad = False
        self.vgg = vgg

    def forward(self, pred, alpha, low, gt):
        # Pixel & Structure (Details)
        loss_pixel = 0.8 * self.l1(pred, gt) + 0.2 * self.mse(pred, gt)

        # SSIM call (Ab attribute error nahi aayega)
        loss_ssim = 1 - self.ssim_loss(pred, gt)

        # Focus (DSLR Sharpness)
        loss_focus = self.laplacian_focus_loss(pred, gt)

        # Dynamic Exposure (Adaptive Day/Night)
        with torch.no_grad():
            low_mean = torch.mean(low, dim=(1,2,3))
            target_exp = torch.where(low_mean < 0.3, torch.tensor(0.6).to(self.device), low_mean + 0.05)
        avg_intensity = F.avg_pool2d(pred, 16).mean(dim=(1,2,3))
        loss_exp = torch.mean((avg_intensity - target_exp)**2)

        # Color & Noise
        loss_col = self.color_constancy_loss(pred, gt)
        loss_denoise = self.edge_aware_tv_loss(pred)
        loss_vgg = self.l1(self.vgg(pred), self.vgg(gt))

        # Final Weighted Loss
        total_loss = (1.0 * loss_pixel) + (25.0 * loss_ssim) + \
                     (20.0 * loss_focus) + (10.0 * loss_exp) + \
                     (8.0 * loss_col) + (15.0 * loss_denoise) + \
                     (1.0 * loss_vgg)

        return total_loss


    def ssim_loss(self, img1, img2, window_size=11):
        mu1 = F.avg_pool2d(img1, window_size, stride=1, padding=window_size//2)
        mu2 = F.avg_pool2d(img2, window_size, stride=1, padding=window_size//2)
        s1q = F.avg_pool2d(img1*img1, window_size, stride=1, padding=window_size//2) - mu1**2
        s2q = F.avg_pool2d(img2*img2, window_size, stride=1, padding=window_size//2) - mu2**2
        s12 = F.avg_pool2d(img1*img2, window_size, stride=1, padding=window_size//2) - mu1*mu2
        c1, c2 = 0.01**2, 0.03**2
        ssim_map = ((2*mu1*mu2 + c1)*(2*s12 + c2)) / ((mu1**2 + mu2**2 + c1)*(s1q + s2q + c2))
        return ssim_map.mean()

    def laplacian_focus_loss(self, pred, gt):
        lap = torch.tensor([[0, 1, 0], [1, -4, 1], [0, 1, 0]], dtype=torch.float32).view(1,1,3,3).to(self.device)
        def get_lap(img):
            return torch.cat([F.conv2d(img[:, i:i+1, :, :], lap, padding=1) for i in range(3)], dim=1)
        return self.l1(get_lap(pred), get_lap(gt))

    def edge_aware_tv_loss(self, img):
        h_x = img[:, :, 1:, :] - img[:, :, :-1, :]
        w_x = img[:, :, :, 1:] - img[:, :, :, :-1]
        return torch.mean(torch.exp(-15 * torch.abs(h_x)) * torch.abs(h_x)) + \
               torch.mean(torch.exp(-15 * torch.abs(w_x)) * torch.abs(w_x))

    def color_constancy_loss(self, x, y):
        return 1 - F.cosine_similarity(x.mean(dim=(2,3)), y.mean(dim=(2,3)), dim=1).mean()

class FusedTrainer:
    def __init__(self, model, criterion, optimizer, scheduler):
        self.optimizer = optimizer
        self.scheduler = scheduler
        self.device = device or torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        self.model = model.to(self.device)
        self.criterion = criterion.to(self.device)
        self.best_loss = float('inf')
        self.best_model_path = None
        self.denoiser = DenoiseBlock(3).to(self.device)
        self.color_corrector = ColorCorrection().to(self.device)


    def show_live_stats(self, running_loss, n_batches, idx, start_time, epoch, total_epochs):
        # Stats calculation
        # Formatting the progress bar
        current_step = idx + 1
        avg_loss = running_loss / current_step

        # create [====>.....] string
        bar_width = 30
        progress = int(current_step / n_batches * bar_width)
        bar = '='* progress + '=>' + "." * (bar_width - progress - 1)

        # Timing
        elapsed = time.time() - start_time
        step_time = (elapsed / current_step) * 1000 # 1000 ms per batch

        # The Magic line
        output = (f"\rEpoch: {epoch}/{total_epochs} - "
                  f"{current_step}/{n_batches} [{bar}]"
                  f"- {step_time:.0f}ms/step - train_loss: {avg_loss:.4f}")

        sys.stdout.write(output)
        sys.stdout.flush()

    def _train_epoch(self, loader, epoch, total_epochs):
        self.model.train()
        train_loss = 0.0
        n_batches = len(loader)
        start_time = time.time()

        for i, (x, y) in enumerate(loader):
            self.model.train()
            self.model.retinex_net.eval()
            self.model.zerodce_net.eval()
            x = x.to(self.device)
            self.optimizer.zero_grad()
            pred, alpha = self.model(x)
            pred = self.denoiser(pred)
            pred = self.color_corrector(pred)
            loss = self.criterion(pred, alpha, x, y.to(self.device))
            loss.backward()
            torch.nn.utils.clip_grad_norm_(self.model.parameters(), 0.1)
            self.optimizer.step()
            train_loss += loss.item()
            self.show_live_stats(train_loss, n_batches, i, start_time, epoch, total_epochs)
        return train_loss/n_batches

    def _validate(self, loader):
        self.model.eval()
        val_loss = 0.0
        with torch.no_grad():
            for x,y in loader:
                x = x.to(self.device)
                pred, alpha = self.model(x)
                pred = self.denoiser(pred)
                pred = self.color_corrector(pred)
                loss = self.criterion(pred, alpha, x, y.to(self.device))
                val_loss += loss.item()

        val_loss = val_loss / len(loader)
        sys.stdout.write(f" - val_loss: {val_loss:.4f}")
        sys.stdout.flush()
        return val_loss



    def fit(self, train_loader, val_loader, epochs, save_model_path, model_name):
        if self.best_model_path is None:
            self.best_model_path = os.path.join(save_model_path, model_name)
        for epoch in range(1, epochs+1):
            train_loss = self._train_epoch(train_loader, epoch, epochs)
            val_loss = self._validate(val_loader)
            diff = abs(train_loss - val_loss)
            if (diff < 5) and (val_loss < self.best_loss):
                old_best = self.best_loss
                self.best_loss = val_loss
                torch.save(self.model.state_dict(), self.best_model_path)
                sys.stdout.write(f" - val_loss improved from {old_best:.4f} to {val_loss:.4f} (diff: {diff:.4f}) and model saved!")
                sys.stdout.flush()
            if self.scheduler:
                self.scheduler.step()
            print()



    def predict(self, x):
        with torch.no_grad():
            return self.model(x.to(self.device))


    def load_best_model(self):
        if not self.best_model_path:
            raise ValueError("No best model found. Please train the model first.")
        self.model.load_state_dict(torch.load(self.best_model_path))

    def load_best_model_for_inference(self, path=None):
        if path:
            self.best_model_path = path
            self.model.load_state_dict(torch.load(self.best_model_path))
            print(f"Best model from {self.best_model_path} loaded succeessfully!")

fused_num_epochs = 5

fused_model = FusionModel(unet_model, dce_model)
criterion = FusionLoss()
optimizer = optim.AdamW(fused_model.parameters(), lr=1e-4, betas=(0.9, 0.999), weight_decay=0.01)
scheduler = optim.lr_scheduler.CosineAnnealingLR(optimizer, T_max=fused_num_epochs, eta_min=1e-7)

fused_trainer = FusedTrainer(fused_model, criterion, optimizer, scheduler)

fused_trainer.fit(train_loader, epochs=fused_num_epochs, val_loader=val_loader, save_model_path=save_model_path, model_name=fused_model_name)

# fused_trainer.load_best_model_for_inference("/kaggle/input/models/shaileshkumarvishwak/llie-fused-models/pytorch/default/1/best-fused-model.pth")

print("RetinexNet:\t", end='')
calculate_scores(fused_trainer, val_loader, name='unet')
print("DCENet:\t", end='')
calculate_scores(fused_trainer, val_loader, name='dcenet')
print("FusionNet:\t", end='')
calculate_scores(fused_trainer, val_loader, name='fusion')

visualize_results(fused_trainer, val_loader, name='fusion')

visualize_results(fused_trainer, test_loader, name='fusion', test_data=True)

import torch
import numpy as np
import cv2
from torch.utils.data import DataLoader

def get_ultra_sharp_mask(patch_size, fade_width=64):
    """
    Creates a mask that is 1.0 in the center and drops off sharply at edges.
    The cubic power (pow 3) ensures the center 'truth' dominates, fixing blur.
    """
    mask = torch.ones((1, patch_size, patch_size), dtype=torch.float32)
    ramp = torch.linspace(0, 1, fade_width)
    # Cubic ramp for a much sharper 'sharpness' zone
    ramp = torch.pow(ramp, 3)

    for i in range(fade_width):
        val = ramp[i]
        mask[:, i, :] *= val           # Top
        mask[:, -(i+1), :] *= val      # Bottom
        mask[:, :, i] *= val           # Left
        mask[:, :, -(i+1)] *= val      # Right
    return mask

def combine_tensor_patches(patch_tensors, coords, original_size, padded_size, patch_size=256):
    h, w = original_size
    nh, nw = padded_size

    canvas = torch.zeros((3, nh, nw), dtype=torch.float32)
    weight_sum = torch.zeros((1, nh, nw), dtype=torch.float32)

    # Use a wider fade for smoother color transitions between patches
    mask = get_ultra_sharp_mask(patch_size, fade_width=64)

    for idx, (i, j) in enumerate(coords):
        patch = patch_tensors[idx].cpu().float()

        # 1. RANGE CHECK: Standardize to [0, 1]
        if patch.max() > 1.5:
            patch = patch / 255.0

        canvas[:, i:i+patch_size, j:j+patch_size] += (patch * mask)
        weight_sum[:, i:i+patch_size, j:j+patch_size] += mask

    # Precise Division
    full_tensor = canvas / (weight_sum + 1e-8)
    img_np = full_tensor.permute(1, 2, 0).numpy()

    # COLOR & CONTRAST FIX:
    p98 = np.percentile(img_np, 98)
    if p98 > 0.05:
        img_np = np.clip(img_np / p98, 0, 1)

    # Final Conversion and Precise Crop
    final_img = (img_np * 255.0).astype(np.uint8)
    return final_img[:h, :w, :]

def enhance_image(model, low_img_rgb):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    patch_size = 512
    stride = 256  # Essential 50% overlap for spline blending
    h, w, _ = low_img_rgb.shape

    # Padding to match stride logic
    pad_h = (patch_size - h % stride) % stride + (patch_size - stride)
    pad_w = (patch_size - w % stride) % stride + (patch_size - stride)
    img_padded = cv2.copyMakeBorder(low_img_rgb, 0, pad_h, 0, pad_w, cv2.BORDER_REFLECT)
    nh, nw, _ = img_padded.shape

    # Extract Patches
    patches = []
    coords = []
    for i in range(0, nh - patch_size + 1, stride):
        for j in range(0, nw - patch_size + 1, stride):
            p = img_padded[i:i+patch_size, j:j+patch_size, :]
            patches.append(torch.from_numpy(p).permute(2, 0, 1).float() / 255.0)
            coords.append((i, j))

    # Inference
    loader = DataLoader(patches, batch_size=8)
    enhanced_list = []

    with torch.no_grad():
        for batch in loader:
            out, _ = model.predict(batch.to(device))
            enhanced_list.extend([p.cpu() for p in out])

    return combine_tensor_patches(enhanced_list, coords, (h, w), (nh, nw), patch_size)

path = "/kaggle/input/datasets/shaileshkumarvishwak/custom-llie-dataset/Custom-LLIE-Dataset/Test/low"
inference_img_list = random.sample(os.listdir(path), 15)
print(f"{len(inference_img_list)} images randomly selected from directory!")

for img_name in inference_img_list:
    low_img_path = os.path.join(path, img_name)
    low_img = cv2.imread(low_img_path)
    low_img = cv2.cvtColor(low_img, cv2.COLOR_BGR2RGB)
    enhanced_img = enhance_image(fused_trainer, low_img)
    plt.figure(figsize=(20,30))
    plt.subplot(1,2,1)
    plt.title(f'Low-Light Image')
    plt.imshow(low_img)
    plt.subplot(1,2,2)
    plt.title(f'Enhanced-Light Image')
    plt.imshow(enhanced_img)
    plt.show()

path = "/kaggle/input/datasets/soumikrakshit/dark-face-dataset/image"
inference_img_list = random.sample(os.listdir(path), 25)
print(f"{len(inference_img_list)} images randomly selected from directory!")

for img_name in inference_img_list:
    low_img_path = os.path.join(path, img_name)
    low_img = cv2.imread(low_img_path)
    low_img = cv2.cvtColor(low_img, cv2.COLOR_BGR2RGB) # Model usually expects RGB
    enhanced_img = enhance_image(fused_trainer, low_img)
    plt.figure(figsize=(20,30))
    plt.subplot(1,2,1)
    plt.title(f'Low-Light Image')
    plt.imshow(low_img)
    plt.subplot(1,2,2)
    plt.title(f'Enhanced-Light Image')
    plt.imshow(enhanced_img)
    plt.show()









